version: '3'

volumes:
  esdata:

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    links:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    volumes:
      - ./data:/data
      - ./logstash_conf:/conf
    command: bin/logstash -f /conf/logstash_cache_log_pipeline.conf
    links:
      - elastic
      - kibana
